### ISSUE TITLE
Visual Studio false error

### ISSUE THREAD

**Issue by OpenSemi-de** [idexus/Sharp.UI#2]
Hey,

Visual Studio still shows the auto-property implemention as error, even when the build is succesful and runs

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0738	'EditContainer' does not implement interface member 'IEditContainerProperties.CircuitView'. 'EditContainer.CircuitView' cannot implement 'IEditContainerProperties.CircuitView' because it does not have the matching return type of 'CircuitViewContainer'.	ACDCs (net7.0-android), ACDCs (net7.0-windows10.0.19041.0)	C:\Users\lmnt1\Desktop\OSSpice\ACDCs\Views\Components\Edit\EditContainer.cs	17	Active
`

File EditContainer.cs in ACDCs

**Comment by OpenSemi-de** [comment]
Restarting VS didn't help. It's not a big issue, but i wanted to tell. everything else works fine

**Comment by idexus** [comment]
Hi,

I use VS for Mac (17.5 build 437). Your project compile and run. I get only this exception

```
   at ACDCs.Services.ImageService.BackgroundImageSource(Single width, Single height) in /Users/pawel/Projects/tmp/ACDCs/ACDCs/Services/ImageService.cs:line 37
```

One more thing, you don't need to create `using AbsoluteLayout = Sharp.UI.AbsoluteLayout;` in your class declaration file. Instead, you can import `Sharp.UI` into your namespace (after declaring the namespace).

```cs
using ACDCs.Views.Components.CircuitView;
using Microsoft.Maui.Layouts;

namespace ACDCs.Views.Components.Edit;

using Sharp.UI;  //<<<<<<<<<<<< put this inside (after) namespace

[BindableProperties]
public interface IEditContainerProperties
{
    CircuitViewContainer CircuitView { get; set; }
}

[SharpObject]
public partial class EditContainer : StackLayout, IEditContainerProperties
{
    public EditContainer()
    {
        ...
    }
}
```

**Comment by OpenSemi-de** [comment]
I did that and it worked as you said. This brought up a problem ive seen before... It cant add the GestureRecognizers (two of three) in the CircuitViewContainer.cs . I pushed it as example. It says it cant add Sharp.UIs recognizers as their base interface. Build is broken

**Comment by OpenSemi-de** [comment]
Thanks for the bug report. Since i dont own a mac i cant tell whats the problem there. do you have exception details?

**Comment by idexus** [comment]
You can add gesture recognition like this

```cs
_graphicsView.GestureRecognizers(new GestureRecognizer[]
{
    _tapRecognizer,
    _panRecognizer,
    _pointerRecognizer
});
```

or like this - in the `Sharp.UI` way

```cs
Content = new GraphicsView(out _graphicsView)
    .BackgroundColor(Colors.Transparent)
    .HorizontalOptions(LayoutOptions.Fill)
    .VerticalOptions(LayoutOptions.Fill)
    .GestureRecognizers(new GestureRecognizer[]
    {
        new TapGestureRecognizer(out _tapRecognizer)
            .OnTapped(TapGestureRecognizer_OnTapped),
        new PanGestureRecognizer(out _panRecognizer)
            .OnPanUpdated(PanGestureRecognizer_OnPanUpdated),
        new PointerGestureRecognizer(out _pointerRecognizer)
            .OnPointerMoved(PointerGestureRecognizer_OnPointerMoved)
    });
```

**Comment by idexus** [comment]
Ad your code - canvas is null object reference not set to an instance of an object.

when I commented `BackgroundImageSource = ImageService.BackgroundImageSource(this);` in Startcenter app starts

```
   at ACDCs.Services.ImageService.BackgroundImageSource(Single width, Single height) in /Users/pawel/Projects/tmp/ACDCs/ACDCs/Services/ImageService.cs:line 37
   at ACDCs.Services.ImageService.BackgroundImageSource(ContentPage view) in /Users/pawel/Projects/tmp/ACDCs/ACDCs/Services/ImageService.cs:line 20
   at ACDCs.Views.StartCenterPage.OnLoaded(Object sender, EventArgs e) in /Users/pawel/Projects/tmp/ACDCs/ACDCs/Views/Startcenter.xaml.cs:line 34
   at Microsoft.Maui.Controls.VisualElement.OnLoadedCore() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 409
   at Microsoft.Maui.Platform.ViewExtensions.<>c__DisplayClass40_0.<OnLoaded>b__2(Object _, ViewAttachedToWindowEventArgs __) in D:\a\_work\1\s\src\Core\src\Platform\Android\ViewExtensions.cs:line 497
   at Android.Views.View.IOnAttachStateChangeListenerImplementor.OnViewAttachedToWindow(View attachedView) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 2025
   at Android.Views.View.IOnAttachStateChangeListenerInvoker.n_OnViewAttachedToWindow_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_attachedView) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 1932
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

**Comment by idexus** [comment]
I made update to GestureRecognizers extension methods, and now you can do it your way. I pushed it. The problem was that Maui's gesture recognizers are sealed classes, so not all things can now be done automatically by the generator.

**Comment by OpenSemi-de** [comment]
Thanks for the big report. ill look into this. i'm closong this for now
